### ISSUE TITLE
Android widget

### ISSUE THREAD

**Issue by chrisbraucker** [BetterArguruments/nofapp#9]
Native android widget displaying the current streak, maybe with a 'next achievement' indicator of sorts.
The [App Widgets](https://developer.android.com/guide/topics/appwidgets/index.html) developer guide seems to be a good start.

Updating the widget is done via onUpdate(). For this to work, read-only database access is needed to fetch the last relapse date.
A single 1x1 scalable widget should suffice, maybe with functionality to start a specific intent on tapping, like entering data/sex/relapse or showing latest stats.
- [x] widget with counter
- [ ] widget update on changes in app
- [x] set non wakelock alarm to update widget daily

**Comment by chrisbraucker** [comment]
Regarding widget updates on changes in app, I see two options:
- update on app load, whether or not changes actually happen
- implement a plugin as [suggested here](http://forum.ionicframework.com/t/calling-native-code-sdks-from-ionic/12748) and call on demand

or rather implement the former and add the latter as needed.

**Comment by olieidel** [comment]
The second solution sounds more complex, but better. In case of relapse, I suppose that it wouldn't work if we only update the widget on app load, as the widget would still need to be updated.

**Comment by chrisbraucker** [comment]
Right now, the widget gets updated every time the user closes (pauses) an activity that extends from MainActivity. Meaning: Press the Back or Home button and the widget updates.
